from enum import Enum


class ResponseType(str, Enum):
    """Every possible response type the backend can produce."""

    GREETING = "GREETING"
    HELP = "HELP"
    JOURNEY_SUMMARY = "JOURNEY_SUMMARY"
    STATION_LIST = "STATION_LIST"
    TRAIN_PROFILE = "TRAIN_PROFILE"
    STATION_PROFILE = "STATION_PROFILE"
    ROUTE_OVERVIEW = "ROUTE_OVERVIEW"
    ROUTE_EXPLANATION = "ROUTE_EXPLANATION"
    RECOMMENDATION = "RECOMMENDATION"
    COMPARISON = "COMPARISON"
    CLARIFICATION = "CLARIFICATION"
    ERROR = "ERROR"
    KNOWLEDGE = "KNOWLEDGE"
    GOODBYE = "GOODBYE"
    SMALL_TALK = "SMALL_TALK"
    SCHEDULE_INFO = "SCHEDULE_INFO"
    JOURNEY_INSIGHT = "JOURNEY_INSIGHT"
    BOOKING = "BOOKING"
    MULTI_MODAL = "MULTI_MODAL"
    UNKNOWN = "UNKNOWN"
